### Here I have built a different dataset for each disaster. The format is panel, with country-year units.

In [25]:
import pandas as pd
import numpy as np

In [26]:
df1 = pd.read_csv('/Volumes/NJ_4TB/EMDAT/EMDAT.csv', skipinitialspace=True, skiprows=6)

/Users/nitashajhala/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (24,25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [27]:
disasters = pd.unique(df1['Disaster Type'])
countries = pd.unique(df1['Country'])
print('# Disaster types: ', len(disasters) )
print('# Countries : ', len(countries) )
#NaNs in interested columns tobe considered 0
df1['Total Deaths'].fillna(0, inplace = True)
df1['Total Affected'].fillna(0, inplace = True)
df1["Total Damages, Adjusted ('000 US$)"].fillna(0, inplace = True)
start_year = 1984
end_year = 2020

# Disaster types:  18
# Countries :  231

In [31]:
for disaster in disasters:    
    print("Processing disaster: ", disaster)
    disaster_all_dataframes = []
    for country in countries:
        sub_index = (df1['Country'] == country) & (df1['Disaster Type'] == disaster)
        single_year_events = sub_index & (df1['End Year'] == df1['Start Year'])
        multi_year_events = np.where(sub_index & (df1['End Year'] != df1['Start Year']))[0]
        list_of_points = []
        for year in range(start_year, end_year + 1):
            indices = single_year_events & (df1['Year'] == year)
            total_deaths = sum(df1['Total Deaths'][indices])
            total_affected = sum(df1['Total Affected'][indices])
            total_damages_adj = sum(df1["Total Damages, Adjusted ('000 US$)"][indices])
            list_of_points.append({'country':country, 'year':year, 'total_deaths':total_deaths, 'total_affected':total_affected, 'total_damages_adj':total_damages_adj})
        disaster_df = pd.DataFrame.from_records(list_of_points)
        for event in multi_year_events:
            n_years = df1.iloc[event]['End Year'] - df1.iloc[event]['Start Year'] + 1.0
            damage = df1.iloc[event]["Total Damages, Adjusted ('000 US$)"].copy() / n_years
            affected = df1.iloc[event]["Total Affected"] / n_years
            deaths = df1.iloc[event]["Total Deaths"] / n_years
            for year in range( df1.iloc[event]['Start Year'],  df1.iloc[event]['End Year'] + 1):
                if np.where(disaster_df['year'] == year)[0].size>0:
                    r = np.where(disaster_df['year'] == year)[0][0]
                    disaster_df.at[r,'total_deaths'] += deaths
                    disaster_df.at[r,'total_affected'] +=  affected
                    disaster_df.at[r,'total_damages_adj'] += damage
        disaster_all_dataframes.append(disaster_df)
    disaster_all_countries = pd.concat(disaster_all_dataframes)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(11).sum()).add_prefix('r10_')],axis=1)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(10).sum()).add_prefix('r9_')],axis=1)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(9).sum()).add_prefix('r8_')],axis=1)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(8).sum()).add_prefix('r7_')],axis=1)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(7).sum()).add_prefix('r6_')],axis=1)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(6).sum()).add_prefix('r5_')],axis=1)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(5).sum()).add_prefix('r4_')],axis=1)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(4).sum()).add_prefix('r3_')],axis=1)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(3).sum()).add_prefix('r2_')],axis=1)
    disaster_all_countries = pd.concat([disaster_all_countries, disaster_all_countries.groupby('country')[['total_deaths','total_affected','total_damages_adj']].transform(lambda s: s.rolling(2).sum()).add_prefix('r1_')],axis=1)
    disaster_all_countries.to_csv('/Volumes/NJ_4TB/EMDAT/' + disaster + '_EMDAT_panel.csv', encoding='utf-8', index=False) 
#     disaster_all_countries.to_csv(disaster + '_EMDAT_panel.csv', encoding='utf-8', index=False)

Processing disaster:  Storm
Processing disaster:  Earthquake
Processing disaster:  Landslide
Processing disaster:  Flood
Processing disaster:  Wildfire
Processing disaster:  Epidemic
Processing disaster:  Transport accident
Processing disaster:  Industrial accident
Processing disaster:  Miscellaneous accident
Processing disaster:  Drought
Processing disaster:  Volcanic activity
Processing disaster:  Extreme temperature
Processing disaster:  Insect infestation
Processing disaster:  Mass movement (dry)
Processing disaster:  Complex Disasters
Processing disaster:  Impact
Processing disaster:  Animal accident
Processing disaster:  Glacial lake outburst

In [32]:
disaster_all_countries[disaster_all_countries['country']=='India']

,country,year,total_deaths,total_affected,total_damages_adj,r10_total_deaths,r10_total_affected,r10_total_damages_adj,r9_total_deaths,r9_total_affected,...,r4_total_damages_adj,r3_total_deaths,r3_total_affected,r3_total_damages_adj,r2_total_deaths,r2_total_affected,r2_total_damages_adj,r1_total_deaths,r1_total_affected,r1_total_damages_adj
0,India,1984,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,India,1985,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,India,1986,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0
3,India,1987,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,India,1988,0,0,0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,India,1989,0,0,0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,India,1990,0,0,0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,India,1991,0,0,0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,India,1992,0,0,0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,India,1993,0,0,0,NaN,NaN,NaN,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,India,1994,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,India,1995,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,India,1996,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,India,1997,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,India,1998,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,India,1999,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,India,2000,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,India,2001,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,India,2002,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,India,2003,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,India,2004,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,India,2005,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,India,2006,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,India,2007,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,India,2008,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,India,2009,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,India,2010,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,India,2011,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,India,2012,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,India,2013,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,India,2014,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,India,2015,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,India,2016,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,India,2017,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,India,2018,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,India,2019,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,India,2020,0,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
df=pd.read_csv('/Volumes/NJ_4TB/EMDAT/Storm_EMDAT_panel.csv', skipinitialspace=True)
df[df['country']=='India']

,country,year,total_deaths,total_affected,total_damages_adj,r10_total_deaths,r10_total_affected,r10_total_damages_adj,r9_total_deaths,r9_total_affected,...,r4_total_damages_adj,r3_total_deaths,r3_total_affected,r3_total_damages_adj,r2_total_deaths,r2_total_affected,r2_total_damages_adj,r1_total_deaths,r1_total_affected,r1_total_damages_adj
2405,India,1984,524.0,1335000.0,87198.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,524.0,1335000.0,87198.0
2406,India,1985,178.0,105000.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,702.0,1440000.0,87198.0,178.0,105000.0,0.0
2407,India,1986,390.0,3300100.0,644483.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1092.0,4740100.0,731681.0,568.0,3405100.0,644483.0,390.0,3300100.0,644483.0
2408,India,1987,166.0,80000.0,0.0,NaN,NaN,NaN,NaN,NaN,...,731681.0,734.0,3485100.0,644483.0,556.0,3380100.0,644483.0,166.0,80000.0,0.0
2409,India,1988,74.0,1900000.0,28451.0,NaN,NaN,NaN,NaN,NaN,...,672934.0,630.0,5280100.0,672934.0,240.0,1980000.0,28451.0,74.0,1900000.0,28451.0
2410,India,1989,93.0,3700000.0,0.0,NaN,NaN,NaN,NaN,NaN,...,672934.0,333.0,5680000.0,28451.0,167.0,5600000.0,28451.0,93.0,3700000.0,0.0
2411,India,1990,1843.0,4100000.0,5730129.0,NaN,NaN,NaN,NaN,NaN,...,5758580.0,2010.0,9700000.0,5758580.0,1936.0,7800000.0,5730129.0,1843.0,4100000.0,5730129.0
2412,India,1991,125.0,25000.0,0.0,NaN,NaN,NaN,NaN,NaN,...,5758580.0,2061.0,7825000.0,5730129.0,1968.0,4125000.0,5730129.0,125.0,25000.0,0.0
2413,India,1992,85.0,100.0,0.0,NaN,NaN,NaN,3478.0,14545200.0,...,5730129.0,2053.0,4125100.0,5730129.0,210.0,25100.0,0.0,85.0,100.0,0.0
2414,India,1993,186.0,72500.0,179160.0,3664.0,14617700.0,6669421.0,3140.0,13282700.0,...,5909289.0,396.0,97600.0,179160.0,271.0,72600.0,179160.0,186.0,72500.0,179160.0
2415,India,1994,219.0,428600.0,33350.0,3359.0,13711300.0,6615573.0,3181.0,13606300.0,...,212510.0,490.0,501200.0,212510.0,405.0,501100.0,212510.0,219.0,428600.0,33350.0
2416,India,1995,222.0,12000.0,82034.0,3403.0,13618300.0,6697607.0,3013.0,10318200.0,...,294544.0,627.0,513100.0,294544.0,441.0,440600.0,115384.0,222.0,12000.0,82034.0
2417,India,1996,1537.0,9177100.0,2475578.0,4550.0,19495300.0,8528702.0,4384.0,19415300.0,...,2770122.0,1978.0,9617700.0,2590962.0,1759.0,9189100.0,2557612.0,1537.0,9177100.0,2475578.0
2418,India,1997,25.0,0.0,0.0,4409.0,19415300.0,8528702.0,4335.0,17515300.0,...,2590962.0,1784.0,9189100.0,2557612.0,1562.0,9177100.0,2475578.0,25.0,0.0,0.0
2419,India,1998,3471.0,4661393.0,760516.0,7806.0,22176693.0,9260767.0,7713.0,18476693.0,...,3318128.0,5033.0,13838493.0,3236094.0,3496.0,4661393.0,760516.0,3471.0,4661393.0,760516.0
2420,India,1999,10378.0,13870008.0,4645627.0,18091.0,32346701.0,13906394.0,16248.0,28246701.0,...,7881721.0,13874.0,18531401.0,5406143.0,13849.0,18531401.0,5406143.0,10378.0,13870008.0,4645627.0
2421,India,2000,0.0,30000.0,0.0,16248.0,28276701.0,8176265.0,16123.0,28251701.0,...,5406143.0,13849.0,18561401.0,5406143.0,10378.0,13900008.0,4645627.0,0.0,30000.0,0.0
2422,India,2001,99.0,27000.0,0.0,16222.0,28278701.0,8176265.0,16137.0,28278601.0,...,5406143.0,10477.0,13927008.0,4645627.0,99.0,57000.0,0.0,99.0,27000.0,0.0
2423,India,2002,144.0,15250.0,599.0,16281.0,28293851.0,8176864.0,16095.0,28221351.0,...,4646226.0,243.0,72250.0,599.0,243.0,42250.0,599.0,144.0,15250.0,599.0
2424,India,2003,164.0,531314.0,61903.0,16259.0,28752665.0,8059607.0,16040.0,28324065.0,...,62502.0,407.0,573564.0,62502.0,308.0,546564.0,62502.0,164.0,531314.0,61903.0
2425,India,2004,0.0,0.0,0.0,16040.0,28324065.0,8026257.0,15818.0,28312065.0,...,62502.0,308.0,546564.0,62502.0,164.0,531314.0,61903.0,0.0,0.0,0.0
2426,India,2005,82.0,68590.0,0.0,15900.0,28380655.0,7944223.0,14363.0,19203555.0,...,62502.0,246.0,599904.0,61903.0,82.0,68590.0,0.0,82.0,68590.0,0.0
2427,India,2006,190.0,150300.0,0.0,14553.0,19353855.0,5468645.0,14528.0,19353855.0,...,61903.0,272.0,218890.0,0.0,272.0,218890.0,0.0,190.0,150300.0,0.0
2428,India,2007,0.0,0.0,0.0,14528.0,19353855.0,5468645.0,11057.0,14692462.0,...,0.0,272.0,218890.0,0.0,190.0,150300.0,0.0,0.0,0.0,0.0
2429,India,2008,111.0,50.0,30052.0,11168.0,14692512.0,4738181.0,790.0,822504.0,...,30052.0,301.0,150350.0,30052.0,111.0,50.0,30052.0,111.0,50.0,30052.0
2430,India,2009,218.0,5109085.0,361911.0,1008.0,5931589.0,454465.0,1008.0,5901589.0,...,391963.0,329.0,5109135.0,391963.0,329.0,5109135.0,391963.0,218.0,5109085.0,361911.0
2431,India,2010,287.0,507080.0,0.0,1295.0,6408669.0,454465.0,1196.0,6381669.0,...,391963.0,616.0,5616215.0,391963.0,505.0,5616165.0,361911.0,287.0,507080.0,0.0
2432,India,2011,106.0,250050.0,432188.0,1302.0,6631719.0,886653.0,1158.0,6616469.0,...,824151.0,611.0,5866215.0,794099.0,393.0,757130.0,432188.0,106.0,250050.0,432188.0
2433,India,2012,40.0,70000.0,0.0,1198.0,6686469.0,886054.0,1034.0,6155155.0,...,794099.0,433.0,827130.0,432188.0,146.0,320050.0,432188.0,40.0,70000.0,0.0
2434,India,2013,106.0,13230004.0,994852.0,1140.0,19385159.0,1819003.0,1140.0,19385159.0,...,1427040.0,252.0,13550054.0,1427040.0,146.0,13300004.0,994852.0,106.0,13230004.0,994852.0
2435,India,2014,119.0,931564.0,7652731.0,1259.0,20316723.0,9471734.0,1177.0,20248133.0,...,9079771.0,265.0,14231568.0,8647583.0,225.0,14161568.0,8647583.0,119.0,931564.0,7652731.0
2436,India,2015,212.0,135100.0,1167297.0,1389.0,20383233.0,10639031.0,1199.0,20232933.0,...,9814880.0,437.0,14296668.0,9814880.0,331.0,1066664.0,8820028.0,212.0,135100.0,1167297.0
2437,India,2016,128.0,0.0,1078348.0,1327.0,20232933.0,11717379.0,1327.0,20232933.0,...,10893228.0,459.0,1066664.0,9898376.0,340.0,135100.0,2245645.0,128.0,0.0,1078348.0
2438,India,2017,940.0,123252.0,0.0,2267.0,20356185.0,11717379.0,2156.0,20356135.0,...,9898376.0,1280.0,258352.0,2245645.0,1068.0,123252.0,1078348.0,940.0,123252.0,0.0
2439,India,2018,625.0,853650.0,2209782.0,2781.0,21209785.0,13897109.0,2563.0,16100700.0,...,4455427.0,1693.0,976902.0,3288130.0,1565.0,976902.0,2209782.0,625.0,853650.0,2209782.0
2440,India,2019,172.0,20130000.0,1832328.0,2735.0,36230700.0,15367526.0,2448.0,35723620.0,...,5120458.0,1737.0,21106902.0,4042110.0,797.0,20983650.0,4042110.0,172.0,20130000.0,1832328.0
2441,India,2020,121.0,18007500.0,14920000.0,2569.0,53731120.0,30287526.0,2463.0,53481070.0,...,18962110.0,918.0,38991150.0,18962110.0,293.0,38137500.0,16752328.0,121.0,18007500.0,14920000.0